# Generated by Django 4.2 on 2023-05-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageView', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='Images',
            field=models.ImageField(upload_to='photos/Image'),
        ),
    ]
