# Generated by Django 4.2 on 2023-05-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageView', '0003_alter_image_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='Images',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
