# Generated by Django 4.2 on 2023-05-08 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
        ('ImageView', '0005_image_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='UserName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.register'),
        ),
    ]
