# Generated by Django 4.2 on 2023-05-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageView', '0006_alter_image_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='UserName',
            field=models.CharField(max_length=25),
        ),
    ]
